problem3_1: pi_multi-thread_mutex.o
	gcc pi_multi-thread_mutex.o -o problem3_1 -pthread
pi_multi-thread_mutex.o: pi_multi-thread_mutex.c
	gcc -c pi_multi-thread_mutex.c 
problem3_2: pi_multi-thread_semaphore.o
	gcc pi_multi-thread_semaphore.o -o problem3_2 -pthread
pi_multi-thread_semaphore.o: pi_multi-thread_semaphore.c
	gcc -c pi_multi-thread_semaphore.c
