problem2_1: nosynch.o
	gcc nosynch.o -o problem2_1 -pthread
nosynch.o: nosynch.c 
	gcc -c nosynch.c
problem2_2: cond_usg.o
	gcc cond_usg.o -o problem2_2 -pthread
cond_usg.o: cond_usg.c
	gcc -c cond_usg.c


